import EditorialRequestsClient from "@/components/EditorialRequestsClient";
import { demoProject } from "@/lib/demo-workspace";
import { Panel, StatusPill, WorkspacePage } from "@/components/WorkspaceShell";

export const metadata = { title: "Progetti editoriali — Kalamos AI" };

export default function ProjectsPage() {
  return <WorkspacePage eyebrow="Version intelligence · working prototype" title={demoProject.title} description="La firma non azzera la memoria. Il progetto eredita il razionale di acquisizione e lo usa come contesto durante le revisioni." actions={<><StatusPill tone="warning">{demoProject.health}</StatusPill><span className="rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-slate-600 shadow-sm">Deadline {demoProject.nextDeadline}</span></>}>
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-6"><Panel title="Project context" subtitle={`${demoProject.author} · ${demoProject.imprint} · ${demoProject.status}`}><div className="p-6"><div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-accento">Perché è arrivato qui</div><p className="mt-3 font-serif text-xl leading-8 text-inchiostro">“{demoProject.acquisitionReason}”</p><p className="mt-4 text-xs leading-5 text-slate-400">Decision memory · contesto dimostrativo</p></div></Panel><Panel title="Versioni"><div className="divide-y divide-[#14213d]/7">{demoProject.versions.map((v) => <div key={v.version} className="grid grid-cols-[60px_1fr_auto] items-center gap-4 px-5 py-4"><div className="font-serif text-xl font-semibold text-inchiostro">{v.version}</div><div><div className="text-sm font-medium text-slate-700">{v.date}</div><div className="text-xs text-slate-400">{v.words.toLocaleString("it-IT")} parole</div></div><StatusPill tone={v.state === "In revisione" ? "warning" : "success"}>{v.state}</StatusPill></div>)}</div></Panel></div><div className="space-y-6"><Panel title="Cosa è cambiato · V2 → V3" subtitle="Confronto semantico dimostrativo, non semplice diff carattere-per-carattere."><ol className="divide-y divide-[#14213d]/7">{demoProject.semanticDiff.map((x, i) => <li key={x} className="flex gap-4 px-5 py-4 sm:px-6"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#14213d]/6 text-xs font-semibold text-inchiostro">{i + 1}</span><p className="text-sm leading-6 text-slate-600">{x}</p></li>)}</ol></Panel><Panel title="Richieste editoriali" subtitle="Lo stato è modificabile e persiste nel browser; la chiusura resta sempre umana."><EditorialRequestsClient requests={demoProject.requests} /></Panel></div></div>
  </WorkspacePage>;
}
